# Generated by Django 2.0.2 on 2018-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_heading',
            field=models.CharField(max_length=200),
        ),
    ]
